In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/penguin/penguins_lter.csv


In [2]:
penguins_df=pd.read_csv('/kaggle/input/penguin/penguins_lter.csv')

In [3]:
penguins_df.head()

studyName  Sample Number                              Species  Region  \
0   PAL0708              1  Adelie Penguin (Pygoscelis adeliae)  Anvers   
1   PAL0708              2  Adelie Penguin (Pygoscelis adeliae)  Anvers   
2   PAL0708              3  Adelie Penguin (Pygoscelis adeliae)  Anvers   
3   PAL0708              4  Adelie Penguin (Pygoscelis adeliae)  Anvers   
4   PAL0708              5  Adelie Penguin (Pygoscelis adeliae)  Anvers   

      Island               Stage Individual ID Clutch Completion  Date Egg  \
0  Torgersen  Adult, 1 Egg Stage          N1A1               Yes  11/11/07   
1  Torgersen  Adult, 1 Egg Stage          N1A2               Yes  11/11/07   
2  Torgersen  Adult, 1 Egg Stage          N2A1               Yes  11/16/07   
3  Torgersen  Adult, 1 Egg Stage          N2A2               Yes  11/16/07   
4  Torgersen  Adult, 1 Egg Stage          N3A1               Yes  11/16/07   

   Culmen Length (mm)  Culmen Depth (mm)  Flipper Length (mm)  Body Mass (g)  \
0                39.1               18.7                181.0         3750.0   
1                39.5               17.4                186.0         3800.0   
2                40.3               18.0                195.0         3250.0   
3                 NaN                NaN                  NaN            NaN   
4                36.7               19.3                193.0         3450.0   

      Sex  Delta 15 N (o/oo)  Delta 13 C (o/oo)  \
0    MALE                NaN                NaN   
1  FEMALE            8.94956          -24.69454   
2  FEMALE            8.36821          -25.33302   
3     NaN                NaN                NaN   
4  FEMALE            8.76651          -25.32426   

                         Comments  
0  Not enough blood for isotopes.  
1                             NaN  
2                             NaN  
3              Adult not sampled.  
4                             NaN

In [4]:
penguins_df.shape

(344, 17)

In [5]:
penguins_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   studyName            344 non-null    object 
 1   Sample Number        344 non-null    int64  
 2   Species              344 non-null    object 
 3   Region               344 non-null    object 
 4   Island               344 non-null    object 
 5   Stage                344 non-null    object 
 6   Individual ID        344 non-null    object 
 7   Clutch Completion    344 non-null    object 
 8   Date Egg             344 non-null    object 
 9   Culmen Length (mm)   342 non-null    float64
 10  Culmen Depth (mm)    342 non-null    float64
 11  Flipper Length (mm)  342 non-null    float64
 12  Body Mass (g)        342 non-null    float64
 13  Sex                  334 non-null    object 
 14  Delta 15 N (o/oo)    330 non-null    float64
 15  Delta 13 C (o/oo)    331 non-null    flo

In [6]:
penguins_df.describe()

Sample Number  Culmen Length (mm)  Culmen Depth (mm)  \
count     344.000000          342.000000         342.000000   
mean       63.151163           43.921930          17.151170   
std        40.430199            5.459584           1.974793   
min         1.000000           32.100000          13.100000   
25%        29.000000           39.225000          15.600000   
50%        58.000000           44.450000          17.300000   
75%        95.250000           48.500000          18.700000   
max       152.000000           59.600000          21.500000   

       Flipper Length (mm)  Body Mass (g)  Delta 15 N (o/oo)  \
count           342.000000     342.000000         330.000000   
mean            200.915205    4201.754386           8.733382   
std              14.061714     801.954536           0.551770   
min             172.000000    2700.000000           7.632200   
25%             190.000000    3550.000000           8.299890   
50%             197.000000    4050.000000           8.652405   
75%             213.000000    4750.000000           9.172123   
max             231.000000    6300.000000          10.025440   

       Delta 13 C (o/oo)  
count         331.000000  
mean          -25.686292  
std             0.793961  
min           -27.018540  
25%           -26.320305  
50%           -25.833520  
75%           -25.062050  
max           -23.787670

In [7]:
penguins_df.isnull().sum()

studyName                0
Sample Number            0
Species                  0
Region                   0
Island                   0
Stage                    0
Individual ID            0
Clutch Completion        0
Date Egg                 0
Culmen Length (mm)       2
Culmen Depth (mm)        2
Flipper Length (mm)      2
Body Mass (g)            2
Sex                     10
Delta 15 N (o/oo)       14
Delta 13 C (o/oo)       13
Comments               318
dtype: int64

In [8]:
# now first we will drop the columns that wont be required in model training
columns_drop = ['studyName', 'Sample Number', 'Individual ID', 'Comments', 'Date Egg']
penguins_df = penguins_df.drop(columns=columns_drop)

In [9]:
# of the remaining columns as not many of their values are missing so for simplicity we'll just drop them
penguins_df = penguins_df.dropna()


In [10]:
# just to check if there are any null values
penguins_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 325 entries, 1 to 343
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Species              325 non-null    object 
 1   Region               325 non-null    object 
 2   Island               325 non-null    object 
 3   Stage                325 non-null    object 
 4   Clutch Completion    325 non-null    object 
 5   Culmen Length (mm)   325 non-null    float64
 6   Culmen Depth (mm)    325 non-null    float64
 7   Flipper Length (mm)  325 non-null    float64
 8   Body Mass (g)        325 non-null    float64
 9   Sex                  325 non-null    object 
 10  Delta 15 N (o/oo)    325 non-null    float64
 11  Delta 13 C (o/oo)    325 non-null    float64
dtypes: float64(6), object(6)
memory usage: 33.0+ KB


In [11]:
# importing the necessary libraries
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [12]:
# now we will perform some encoding we will first encode our target column species into numerical values.
l_encode = LabelEncoder()
penguins_df['Species'] = l_encode.fit_transform(penguins_df['Species'])

In [13]:
# now for the below columns we will convert them using binary encoding
categorical = ['Region', 'Island', 'Stage', 'Clutch Completion', 'Sex']
penguins_df = pd.get_dummies(penguins_df, columns=categorical, drop_first=True)

In [14]:
# lets view it again
penguins_df.head()

Species  Culmen Length (mm)  Culmen Depth (mm)  Flipper Length (mm)  \
1        0                39.5               17.4                186.0   
2        0                40.3               18.0                195.0   
4        0                36.7               19.3                193.0   
5        0                39.3               20.6                190.0   
6        0                38.9               17.8                181.0   

   Body Mass (g)  Delta 15 N (o/oo)  Delta 13 C (o/oo)  Island_Dream  \
1         3800.0            8.94956          -24.69454         False   
2         3250.0            8.36821          -25.33302         False   
4         3450.0            8.76651          -25.32426         False   
5         3650.0            8.66496          -25.29805         False   
6         3625.0            9.18718          -25.21799         False   

   Island_Torgersen  Clutch Completion_Yes  Sex_FEMALE  Sex_MALE  
1              True                   True        True     False  
2              True                   True        True     False  
4              True                   True        True     False  
5              True                   True       False      True  
6              True                  False        True     False

In [15]:
# seperating the target and feature variables
X = penguins_df.drop(columns=['Species'])
y = penguins_df['Species']     

In [16]:
# lets confirm
print("Shape of X (features):", X.shape)
print("Shape of y (target):", y.shape)

Shape of X (features): (325, 11)
Shape of y (target): (325,)


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
# model training using KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
# training the model
knn.fit(X_train, y_train)
# we'll predict the accuracy of the model
knn_accuracy = knn.score(X_test, y_test)
print("KNN Accuracy:", knn_accuracy)

KNN Accuracy: 0.7384615384615385


In [19]:
from sklearn.svm import SVC
# intialising the model
svm = SVC(kernel='linear')  
# training the model
svm.fit(X_train, y_train)
# we'll predict the accuracy of the model
svm_accuracy = svm.score(X_test, y_test)
print("SVM Accuracy:", svm_accuracy)

SVM Accuracy: 1.0


In [20]:
from sklearn.metrics import classification_report, confusion_matrix

# Evaluating the KNN model
print("KNN Model Evaluation:")
y_pred_knn = knn.predict(X_test)
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))


KNN Model Evaluation:
[[24  4  1]
 [10  3  1]
 [ 1  0 21]]
              precision    recall  f1-score   support

           0       0.69      0.83      0.75        29
           1       0.43      0.21      0.29        14
           2       0.91      0.95      0.93        22

    accuracy                           0.74        65
   macro avg       0.68      0.67      0.66        65
weighted avg       0.71      0.74      0.71        65



In [21]:
# Evaluating the SVM model
print("\nSVM Model Evaluation:")
y_pred_svm = svm.predict(X_test)
print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))


SVM Model Evaluation:
[[29  0  0]
 [ 0 14  0]
 [ 0  0 22]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        22

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65

